# Generated by Django 4.2.1 on 2023-06-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Person',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qno', models.IntegerField(primary_key=True, serialize=False)),
                ('qtext', models.CharField(max_length=50)),
                ('qanswer', models.CharField(max_length=50)),
                ('op1', models.CharField(max_length=50)),
                ('op2', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Question',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('name', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=5)),
                ('score', models.IntegerField()),
            ],
            options={
                'db_table': 'score',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('rno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('marks', models.IntegerField()),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('mobno', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('imagepath', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('mobno', models.IntegerField()),
            ],
            options={
                'db_table': 'userdata',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=40)),
                ('upass', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
