
from django.urls import path
from . import views

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
      
urlpatterns = [
        path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
        path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
        path('visitGoogle',views.visitGoogle),  
        path("test/",views.ClassBaseView.as_view()),
        path("helloworld",views.hello_world),
        path("getUser/<username>",views.getUser),
        path("getUser2/<username>",views.getUser2),
        path("getallUsers",views.getallUsers),
        path("getallusers2",views.getallusers2),
        path("addUser",views.addUser),
        path("addUser2",views.addUser2),
        path("deleteUser/<username>",views.deleteUser),
        path("deleteUser2/<username>",views.deleteUser2),
        path('updateUser',views.updateUser),
        path('updateUser2',views.updateUser2),
        path('sendJsonList',views.sendJsonList),
        path('hello/', views.hello),
        path('receiveData', views.getJSONData),
        path('helloDjango/', views.helloDjango),
        path('', views.homepage),
        path('login/', views.login),
        path('next/',views.next),
        path('previous/',views.previous),
        path('storeresponse/',views.storeresponse),
        path('calculatescore/',views.calculatescore),
        path('score/',views.score),
        path('logout/',views.logout),
        path('login1/',views.login1),
        path('register/',views.register),
        path('login2/',views.login2),
        path('getRemainingTime/',views.getRemainingTime),
        path('saveQuestions/',views.saveQuestions),
        path('viewQuestion/',views.viewQuestion),
        path('updateQuestion/',views.updateQuestion),
        path('deleteQuestion/',views.deleteQuestion),
        path('showregister/',views.showregister),
        path('checkUsername',views.checkUsername),
        path('databaseop',views.databaseop),
        path('saveUserData',views.saveUserData),
        path('logins',views.logins),
        path('next',views.nextQuestion),
        path('score',views.result),
        path('endpage',views.endpage),
        path('previousQuestion',views.previousQuestion),
        path('storeanswer',views.storeanswer),
        path('answerschecking',views.answerschecking),
        path('uploadFile/',views.uploadFile),
        path('getStudent/<rollnumber>',views.getStudent),
        path('receiveStudent',views.receiveStudent),
        path('saveStudent',views.saveStudent),
        path('updateStudent',views.updateStudent),
        path('deleteStudent/<rollnumber>',views.deleteStudent),
        path('getAllStudents',views.getAllStudents),
        path('addition',views.addition),
        path('subtraction',views.subtraction),
        path('setSession',views.setSession),
        path('getSession',views.getSession),
        path('removeSession',views.removeSession)

    ]  
